spring:
  application:
    name: marchive-backend
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always