spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/marchive
    username: root
    password: ${DB_PASSWORD}

jwt:
  secret: local-test-secret-key-must-be-32-bytes-or-longer!!

google:
  client-id: local-test-client-id